WebMVCEcommerce/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using StandardLibrary.Comment;
using WebMVCEcommerce.Services.Comment;

namespace WebMVCEcommerce.Controllers
{
	public class CommentController : Controller
	{
		private readonly ICommentApiClient _commentApiClient;

		public CommentController(ICommentApiClient commentApiClient)
		{
			_commentApiClient = commentApiClient;
		}

		[HttpPost]
		public async Task<IActionResult> Create(CreateCommentDto commentDto)
		{
			if (!ModelState.IsValid)
			{
				return BadRequest(ModelState);
			}
			var createdComment = await _commentApiClient.CreateCommentAsync(commentDto);

			if (createdComment != null)
			{
				return Redirect($"~/Product/Details/{commentDto.ProductId}");
			}

			return View("Error");
		}
	}
}

WebMVCEcommerce/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StandardLibrary.Comment;
using StandardLibrary.Product;
using WebMVCEcommerce.Services.Product;

namespace WebMVCEcommerce.Controllers
{
    public class ProductController : Controller
    {
        private readonly ILogger<ProductController> _logger;
        private readonly IProductApiClient _productApiClient;
		public ProductController(ILogger<ProductController> logger, IProductApiClient productApiClient)
        {
            _logger = logger;
            _productApiClient = productApiClient;
        }
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Get Products from API");
            var products = await _productApiClient.GetProducts();
            //ViewData["Products"] = products;
            return View(products);
        }

		
		public async Task<IActionResult> Details(int id)
		{
			_logger.LogInformation($"Getting product details for ID: {id}");
			var product = await _productApiClient.GetProductById(id);
			if (product == null)
			{
				return NotFound();
			}

			var comments = await _productApiClient.GetProductComments(id);
			var productComment = new ProductCommentDto
			{
				Product = product,
				Comments = comments
			};

			return View(productComment);
		}

	}
}

WebMVCEcommerce/Views/Product/Details.cshtml
@using StandardLibrary.Product
@model ProductCommentDto
 
@{
    ViewData["Title"] = "Details";
}

<section class="sec-product-detail bg0 p-t-65 p-b-60">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-lg-7 p-b-30">
				<div class="p-l-25 p-r-30 p-lr-0-lg">
					<div class="wrap-slick3 flex-sb flex-w">
						@* <div class="wrap-slick3-dots"></div> *@
						@* <div class="wrap-slick3-arrows flex-sb-m flex-w"></div> *@

						<div class="slick3 gallery-lb">
								<div class="wrap-pic-w pos-relative">
									<img src="@Model.Product.ImageURL" alt="IMG-PRODUCT" style="width: 400px; height: 500px;">
								</div>
						</div>
					</div>
				</div>
			</div>

			<div class="col-md-6 col-lg-5 p-b-30">
				<div class="p-r-50 p-t-5 p-lr-0-lg">
					<a asp-controller="Product" asp-action="Index" asp-route-id="">
						<h4 class="mtext-105 cl2 js-name-detail p-b-14">
							@Model.Product.ProductName
						</h4>
					</a>

					<span class="mtext-106 cl2">
						$@Model.Product.Price
					</span>

					<p class="stext-102 cl3 p-t-23">
						@Model.Product.ProductDescription
					</p>

			

						<div class="flex-w flex-r-m p-b-10">
							<div class="size-204 flex-w flex-m respon6-next">
								<div class="wrap-num-product flex-w m-r-20 m-tb-10">
									<div class="btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m">
										<i class="fs-16 zmdi zmdi-minus"></i>
									</div>

									<input class="mtext-104 cl3 txt-center num-product" type="number" name="num-product" value="1">

									<div class="btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m">
										<i class="fs-16 zmdi zmdi-plus"></i>
									</div>
								</div>

								<button class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04 js-addcart-detail">
									Add to cart
								</button>
							</div>
						</div>
					</div>

					<!--  -->
					<div class="flex-w flex-m p-l-100 p-t-40 respon7">
						<div class="flex-m bor9 p-r-10 m-r-11">
							<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 js-addwish-detail tooltip100" data-tooltip="Add to Wishlist">
								<i class="zmdi zmdi-favorite"></i>
							</a>
						</div>

						<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100" data-tooltip="Facebook">
							<i class="fa fa-facebook"></i>
						</a>

						<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100" data-tooltip="Twitter">
							<i class="fa fa-twitter"></i>
						</a>

						<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100" data-tooltip="Google Plus">
							<i class="fa fa-google-plus"></i>
						</a>
					</div>
				</div>
			</div>
		</div>

		<div class="bor10 m-t-50 p-t-43 p-b-40">
			<!-- Tab01 -->
			<div class="tab01">
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
					<li class="nav-item p-b-10">
						<a class="nav-link active" data-toggle="tab" href="#description" role="tab">Description</a>
					</li>

					<li class="nav-item p-b-10">
						<a class="nav-link" data-toggle="tab" href="#reviews" role="tab">Reviews (1)</a>
					</li>
				</ul>

				<!-- Tab panes -->
				<div class="tab-content p-t-43">
					<!-- - -->
					<div class="tab-pane fade show active" id="description" role="tabpanel">
						<div class="how-pos2 p-lr-15-md">
							<p class="stext-102 cl6">
							@Model.Product.ProductDescription
							</p>
						</div>
					</div>

					<!-- - -->
					<div class="tab-pane fade" id="reviews" role="tabpanel">
						<div class="row">
							<div class="col-sm-10 col-md-8 col-lg-6 m-lr-auto">
								<div class="p-b-30 m-lr-15-sm">
									<!-- Review -->
								@foreach (var comment in Model.Comments)
								{
									<div class="flex-w flex-t p-b-68">
										@* <div class="wrap-pic-s size-109 bor0 of-hidden m-r-18 m-t-6">
											<img src="~/images/avatar-01.jpg" alt="AVATAR">
										</div> *@

										<div class="size-207">
											<div class="flex-w flex-sb-m p-b-17">
												<span class="mtext-107 cl2 p-r-20">
													@comment.UserName
												</span>

												<span class="fs-18 cl11">
													@for (int i = 0; i < 5; i++)
													{
														if (i < comment.Rating)
														{
															<i class="zmdi zmdi-star"></i>
														}
														else
														{
															<i class="zmdi zmdi-star-outline"></i>
														}
													}
												</span>
											</div>

											<p class="stext-102 cl6">
												@comment.CommentText
											</p>
										</div>
									</div>
								}

									<!-- Add review -->
									<form asp-controller="Comment" asp-action="Create" class="w-full">
										<input type="text" value="@Model.Product.ProductId" name="ProductId" class="d-none" />
										<h5 class="mtext-108 cl2 p-b-7">
											Add a review
										</h5>

										<p class="stext-102 cl6">
											Your email address will not be published. Required fields are marked *
										</p>

										<div class="flex-w flex-m p-t-50 p-b-23">
											<span class="stext-102 cl3 m-r-16">
												Your Rating
											</span>

											<span class="wrap-rating fs-18 cl11 pointer">
												<i class="item-rating pointer zmdi zmdi-star-outline"></i>
												<i class="item-rating pointer zmdi zmdi-star-outline"></i>
												<i class="item-rating pointer zmdi zmdi-star-outline"></i>
												<i class="item-rating pointer zmdi zmdi-star-outline"></i>
												<i class="item-rating pointer zmdi zmdi-star-outline"></i>
												<input class="dis-none" type="number" name="rating">
											</span>
										</div>

										<div class="row p-b-25">
											<div class="col-12 p-b-5">
												<label class="stext-102 cl3" for="review">Your review</label>
											<textarea class="size-110 bor8 stext-102 cl2 p-lr-20 p-tb-10" id="review" name="CommentText"></textarea>
											</div>

										</div>

										<button class="flex-c-m stext-101 cl0 size-112 bg7 bor11 hov-btn3 p-lr-15 trans-04 m-b-10">
											Submit
										</button>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

WebMVCEcommerce/Views/Product/Index.cshtml
@using StandardLibrary
@using StandardLibrary.Product
@model IEnumerable<ProductDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageURL)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageURL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>